### ISSUE TITLE
Using setStatus: seems to start the progress indicator over each time

### ISSUE THREAD

**Issue by nnhubbard** [TransitApp/SVProgressHUD#415]
I am uploading some files quickly, so I want the status to change to "Uploading Image 1", "Uploading Image 2", etc. But each time I call setStatus: the progress indicator flashes and most times starts over.

Is this intended to be this way? Or is there a method to make seamless status changes and let the progress indicator not be effected?

**Comment by honkmaster** [comment]
We had the same issue with #386. But it should be fixed. Are you on the latest version?

**Comment by nnhubbard** [comment]
Wow, you are fast. I am using the newest version and I am still seeing the issue.

**Comment by honkmaster** [comment]
Ok, that good to know. I will check on the problem right now. Some more questions. What is your first call to show the hud ('showWithStatus:')? What are the approximate time deltas between each 'setStatus:' call?

**Comment by nnhubbard** [comment]
First call is:

`[SVProgressHUD showWithStatus:NSLocalizedString(@"Saving Offline List", nil)];`

Then I am making some image download requests (50+) an calling the following each time: 

`[SVProgressHUD setStatus:[NSString stringWithFormat:@"%@ %lu", NSLocalizedString(@"Downloading Image", nil), (unsigned long)self.downloadIndex]];`

Execution time examples:

- executionTime = 0.030228
- executionTime = 0.015047
- executionTime = 0.017983
- executionTime = 0.017497
- executionTime = 0.019710
- executionTime = 0.017222

**Comment by honkmaster** [comment]
I did a small test: https://www.youtube.com/watch?v=7750boYDFQ0. I see no flickering.

**Comment by honkmaster** [comment]
Oh, i see now. The differences are really very short. Will update my demoe project.

**Comment by nnhubbard** [comment]
Is there a work around?

**Comment by honkmaster** [comment]
Could you check the latest commit?

**Comment by nnhubbard** [comment]
That fixed it! Thank you very much!
